---
git:
  depth: 1
sudo: false
language: node_js
cache:
  directories:
  - node_modules

node_js:
  - "5"
  - "4"
  - iojs
  - "0.12"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8